### ISSUE TITLE
OPEN_SORCE

### ISSUE THREAD

**Issue by redmangospros** [vutondesign/vuton-d3000#1]

**Comment by vutondesign** [comment]
I don't plan on making much of the bot's code open_source as It would give away the bot token and some other stuff.

**Comment by redmangospros** [comment]
but how do ppl knoe it's safe?

**Comment by vutondesign** [comment]
They don't, but why would it not be?

**Comment by redmangospros** [comment]
how do people knoe, that the code iis sfae, isit taking info?

**Comment by redmangospros** [comment]
waffle is slowww

**Comment by vutondesign** [comment]
@redmangospros Because when you add a bot to a server, it shows you what permissions the bot has. (and it's very hard for a bot on discord to take your info)

**Comment by vutondesign** [comment]
What is waffle?

**Comment by redmangospros** [comment]
waffle programing

**Comment by redmangospros** [comment]
what did you use? discord.py
discord.js
discord.cfg

**Comment by vutondesign** [comment]
discord.js

**Comment by redmangospros** [comment]
Cool, can you help me with my discord bot? Please?

**Comment by vutondesign** [comment]
I can't really as you have to build it locally.

**Comment by redmangospros** [comment]
i really don't care of the token,,i have node.js, but i like discord.py better

**Comment by redmangospros** [comment]
hi!
